insert into TRAFODION.XDC_TEST.XDC values(1,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(2,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(3,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(4,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(5,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(6,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(7,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(8,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(9,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(10,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(11,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(12,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(13,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(14,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(15,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(16,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(17,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(18,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(19,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(20,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(21,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(22,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(23,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(24,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(25,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(26,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(27,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(28,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(29,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(30,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(31,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(32,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(33,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(34,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(35,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(36,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(37,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(38,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(39,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(40,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(41,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(42,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(43,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(44,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(45,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(46,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(47,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(48,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(49,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(50,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(51,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(52,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(53,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(54,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(55,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(56,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(57,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(58,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(59,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(60,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(61,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(62,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(63,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(64,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(65,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(66,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(67,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(68,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(69,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(70,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(71,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(72,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(73,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(74,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(75,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(76,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(77,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(78,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(79,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(80,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(81,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(82,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(83,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(84,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(85,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(86,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(87,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(88,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(89,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(90,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(91,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(92,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(93,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(94,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(95,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(96,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(97,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(98,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(99,'llll',123.4);
insert into TRAFODION.XDC_TEST.XDC values(100,'llll',123.4);
upsert into TRAFODION.XDC_TEST.XDC values(301,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(302,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(303,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(304,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(305,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(306,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(307,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(308,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(309,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(310,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(311,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(312,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(313,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(314,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(315,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(316,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(317,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(318,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(319,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(320,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(321,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(322,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(323,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(324,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(325,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(326,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(327,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(328,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(329,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(330,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(331,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(332,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(333,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(334,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(335,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(336,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(337,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(338,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(339,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(340,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(341,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(342,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(343,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(344,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(345,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(346,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(347,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(348,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(349,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(350,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(351,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(352,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(353,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(354,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(355,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(356,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(357,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(358,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(359,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(360,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(361,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(362,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(363,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(364,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(365,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(366,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(367,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(368,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(369,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(370,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(371,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(372,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(373,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(374,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(375,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(376,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(377,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(378,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(379,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(380,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(381,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(382,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(383,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(384,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(385,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(386,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(387,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(388,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(389,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(390,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(391,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(392,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(393,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(394,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(395,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(396,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(397,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(398,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(399,'kkkk',234.5);
upsert into TRAFODION.XDC_TEST.XDC values(400,'kkkk',234.5);
upsert using load into TRAFODION.XDC_TEST.XDC values(401,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(402,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(403,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(404,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(405,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(406,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(407,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(408,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(409,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(410,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(411,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(412,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(413,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(414,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(415,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(416,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(417,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(418,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(419,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(420,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(421,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(422,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(423,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(424,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(425,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(426,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(427,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(428,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(429,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(430,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(431,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(432,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(433,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(434,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(435,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(436,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(437,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(438,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(439,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(440,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(441,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(442,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(443,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(444,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(445,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(446,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(447,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(448,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(449,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(450,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(451,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(452,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(453,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(454,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(455,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(456,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(457,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(458,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(459,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(460,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(461,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(462,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(463,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(464,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(465,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(466,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(467,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(468,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(469,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(470,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(471,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(472,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(473,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(474,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(475,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(476,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(477,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(478,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(479,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(480,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(481,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(482,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(483,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(484,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(485,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(486,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(487,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(488,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(489,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(490,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(491,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(492,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(493,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(494,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(495,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(496,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(497,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(498,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(499,'nnnn',345.6);
upsert using load into TRAFODION.XDC_TEST.XDC values(500,'nnnn',345.6);
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 1;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 2;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 3;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 4;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 5;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 6;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 7;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 8;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 9;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 10;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 11;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 12;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 13;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 14;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 15;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 16;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 17;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 18;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 19;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 20;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 21;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 22;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 23;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 24;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 25;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 26;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 27;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 28;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 29;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 30;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 31;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 32;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 33;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 34;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 35;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 36;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 37;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 38;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 39;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 40;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 41;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 42;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 43;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 44;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 45;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 46;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 47;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 48;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 49;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 50;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 51;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 52;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 53;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 54;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 55;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 56;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 57;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 58;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 59;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 60;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 61;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 62;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 63;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 64;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 65;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 66;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 67;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 68;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 69;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 70;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 71;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 72;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 73;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 74;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 75;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 76;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 77;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 78;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 79;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 80;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 81;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 82;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 83;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 84;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 85;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 86;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 87;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 88;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 89;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 90;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 91;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 92;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 93;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 94;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 95;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 96;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 97;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 98;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 99;
update TRAFODION.XDC_TEST.XDC set name='mmmm' where id = 100;
delete from TRAFODION.XDC_TEST.XDC where id=1;
delete from TRAFODION.XDC_TEST.XDC where id=2;
delete from TRAFODION.XDC_TEST.XDC where id=3;
delete from TRAFODION.XDC_TEST.XDC where id=4;
delete from TRAFODION.XDC_TEST.XDC where id=5;
delete from TRAFODION.XDC_TEST.XDC where id=6;
delete from TRAFODION.XDC_TEST.XDC where id=7;
delete from TRAFODION.XDC_TEST.XDC where id=8;
delete from TRAFODION.XDC_TEST.XDC where id=9;
delete from TRAFODION.XDC_TEST.XDC where id=10;
delete from TRAFODION.XDC_TEST.XDC where id=11;
delete from TRAFODION.XDC_TEST.XDC where id=12;
delete from TRAFODION.XDC_TEST.XDC where id=13;
delete from TRAFODION.XDC_TEST.XDC where id=14;
delete from TRAFODION.XDC_TEST.XDC where id=15;
delete from TRAFODION.XDC_TEST.XDC where id=16;
delete from TRAFODION.XDC_TEST.XDC where id=17;
delete from TRAFODION.XDC_TEST.XDC where id=18;
delete from TRAFODION.XDC_TEST.XDC where id=19;
delete from TRAFODION.XDC_TEST.XDC where id=20;
delete from TRAFODION.XDC_TEST.XDC where id=21;
delete from TRAFODION.XDC_TEST.XDC where id=22;
delete from TRAFODION.XDC_TEST.XDC where id=23;
delete from TRAFODION.XDC_TEST.XDC where id=24;
delete from TRAFODION.XDC_TEST.XDC where id=25;
delete from TRAFODION.XDC_TEST.XDC where id=26;
delete from TRAFODION.XDC_TEST.XDC where id=27;
delete from TRAFODION.XDC_TEST.XDC where id=28;
delete from TRAFODION.XDC_TEST.XDC where id=29;
delete from TRAFODION.XDC_TEST.XDC where id=30;
delete from TRAFODION.XDC_TEST.XDC where id=31;
delete from TRAFODION.XDC_TEST.XDC where id=32;
delete from TRAFODION.XDC_TEST.XDC where id=33;
delete from TRAFODION.XDC_TEST.XDC where id=34;
delete from TRAFODION.XDC_TEST.XDC where id=35;
delete from TRAFODION.XDC_TEST.XDC where id=36;
delete from TRAFODION.XDC_TEST.XDC where id=37;
delete from TRAFODION.XDC_TEST.XDC where id=38;
delete from TRAFODION.XDC_TEST.XDC where id=39;
delete from TRAFODION.XDC_TEST.XDC where id=40;
delete from TRAFODION.XDC_TEST.XDC where id=41;
delete from TRAFODION.XDC_TEST.XDC where id=42;
delete from TRAFODION.XDC_TEST.XDC where id=43;
delete from TRAFODION.XDC_TEST.XDC where id=44;
delete from TRAFODION.XDC_TEST.XDC where id=45;
delete from TRAFODION.XDC_TEST.XDC where id=46;
delete from TRAFODION.XDC_TEST.XDC where id=47;
delete from TRAFODION.XDC_TEST.XDC where id=48;
delete from TRAFODION.XDC_TEST.XDC where id=49;
delete from TRAFODION.XDC_TEST.XDC where id=50;
delete from TRAFODION.XDC_TEST.XDC where id=51;
delete from TRAFODION.XDC_TEST.XDC where id=52;
delete from TRAFODION.XDC_TEST.XDC where id=53;
delete from TRAFODION.XDC_TEST.XDC where id=54;
delete from TRAFODION.XDC_TEST.XDC where id=55;
delete from TRAFODION.XDC_TEST.XDC where id=56;
delete from TRAFODION.XDC_TEST.XDC where id=57;
delete from TRAFODION.XDC_TEST.XDC where id=58;
delete from TRAFODION.XDC_TEST.XDC where id=59;
delete from TRAFODION.XDC_TEST.XDC where id=60;
delete from TRAFODION.XDC_TEST.XDC where id=61;
delete from TRAFODION.XDC_TEST.XDC where id=62;
delete from TRAFODION.XDC_TEST.XDC where id=63;
delete from TRAFODION.XDC_TEST.XDC where id=64;
delete from TRAFODION.XDC_TEST.XDC where id=65;
delete from TRAFODION.XDC_TEST.XDC where id=66;
delete from TRAFODION.XDC_TEST.XDC where id=67;
delete from TRAFODION.XDC_TEST.XDC where id=68;
delete from TRAFODION.XDC_TEST.XDC where id=69;
delete from TRAFODION.XDC_TEST.XDC where id=70;
delete from TRAFODION.XDC_TEST.XDC where id=71;
delete from TRAFODION.XDC_TEST.XDC where id=72;
delete from TRAFODION.XDC_TEST.XDC where id=73;
delete from TRAFODION.XDC_TEST.XDC where id=74;
delete from TRAFODION.XDC_TEST.XDC where id=75;
delete from TRAFODION.XDC_TEST.XDC where id=76;
delete from TRAFODION.XDC_TEST.XDC where id=77;
delete from TRAFODION.XDC_TEST.XDC where id=78;
delete from TRAFODION.XDC_TEST.XDC where id=79;
delete from TRAFODION.XDC_TEST.XDC where id=80;
delete from TRAFODION.XDC_TEST.XDC where id=81;
delete from TRAFODION.XDC_TEST.XDC where id=82;
delete from TRAFODION.XDC_TEST.XDC where id=83;
delete from TRAFODION.XDC_TEST.XDC where id=84;
delete from TRAFODION.XDC_TEST.XDC where id=85;
delete from TRAFODION.XDC_TEST.XDC where id=86;
delete from TRAFODION.XDC_TEST.XDC where id=87;
delete from TRAFODION.XDC_TEST.XDC where id=88;
delete from TRAFODION.XDC_TEST.XDC where id=89;
delete from TRAFODION.XDC_TEST.XDC where id=90;
delete from TRAFODION.XDC_TEST.XDC where id=91;
delete from TRAFODION.XDC_TEST.XDC where id=92;
delete from TRAFODION.XDC_TEST.XDC where id=93;
delete from TRAFODION.XDC_TEST.XDC where id=94;
delete from TRAFODION.XDC_TEST.XDC where id=95;
delete from TRAFODION.XDC_TEST.XDC where id=96;
delete from TRAFODION.XDC_TEST.XDC where id=97;
delete from TRAFODION.XDC_TEST.XDC where id=98;
delete from TRAFODION.XDC_TEST.XDC where id=99;
delete from TRAFODION.XDC_TEST.XDC where id=100;
