#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
#

if [ -z $1 ]; then
    echo "Usage: $0 <cluster id (an integer in the range 1-100)>"
    exit 1
fi

declare -i lv_my_peer_id
lv_my_peer_id=$1
if (
	[ $lv_my_peer_id -lt 1 ] ||
	[ $lv_my_peer_id -gt 100 ]
    ); then
    echo "Please provide a cluster id in the range 1-100"
    exit 1
fi

if [ -z $JAVA_HOME ]; then
    echo "The environment variable \$JAVA_HOME has not been set"
    echo "Please set it and run this script again."
    echo
    exit 1;
fi

$JAVA_HOME/bin/java org.apache.hadoop.hbase.client.transactional.HBaseDCZK -setmyid ${lv_my_peer_id} 2>/dev/null
lv_stat=$?
if [[ $lv_stat == 0 ]]; then
    echo "Successfully set the id of this cluster to ${lv_my_peer_id} in the zookeeper database."
    echo "Please restart the Trafodion cluster for this to take effect."
fi

