#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

if [ -z $JAVA_HOME ]; then
    echo "The environment variable \$JAVA_HOME has not been set"
    echo "Please ensure \$TRAF_HOME/sqenv.sh has been sourced."
    echo
    exit 1;
fi

lv_error_log_file=${TRAF_HOME}/logs/xdc_peer_check.log
lv_peerids=`$JAVA_HOME/bin/java org.apache.hadoop.hbase.client.transactional.HBaseDCZK -list 2>${lv_error_log_file} | cut -d: -f1 | sort`
lv_ret=${PIPESTATUS[0]}
if [[ ${lv_ret} != 0 ]]; then
    echo "Error code: ${lv_ret}"
    echo "Error getting the list of peers. Please check ${lv_error_log_file}"
    exit 1;
fi

lv_my_id=`$JAVA_HOME/bin/java org.apache.hadoop.hbase.client.transactional.HBaseDCZK -getmyid 2>${lv_error_log_file}`
lv_ret=$?
if [[ ${lv_ret} != 0 ]]; then
    echo "Error getting my clusterid"
    exit 1;
fi

for lv_peerid in $lv_peerids; do
    if [[ ${lv_peerid} == ${lv_my_id} ]]; then
	continue;
    fi
    echo $lv_peerid
done
