#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
#

function Usage {
    echo
    echo "Usage: $0 {-i <nn> | -h}"
    echo
    echo "-i ID of the peer (A number between 1 and 100 (inclusive))"
    echo
    echo "-h Help "
    echo
}

if [ -z $TRAF_HOME ]; then
    echo
    echo "The TRAF_HOME environment variable does not exist."
    echo "Please ensure sqenv.sh has been sourced."
    echo
    exit 1;
fi

if [ -z $JAVA_HOME ]; then
    echo "The environment variable \$JAVA_HOME has not been set"
    echo "Please ensure \$TRAF_HOME/sqenv.sh has been sourced."
    echo
    exit 1;
fi

declare -i lv_peer_id
declare -i lv_zookeeper_port

let lv_peer_id=0
let lv_zookeeper_port=2181

while getopts "i:h" lv_arg $1 $2 $3 $4 $5 $6 $7 $8 $9
do
    case $lv_arg in 
	i)
	    lv_peer_id=${OPTARG}
	    if (
		    [ $lv_peer_id -lt 1 ] ||
		    [ $lv_peer_id -gt 100 ]
		); then
		echo "Please provide a peer id in the range 1-100"
		exit 1
	    fi
	    ;;
	
	h)
	    lv_help=1
	    Usage
	    exit 0
            ;;
	
	*) 
	    Usage
	    exit 1
	    ;;
    esac
done

if [ ${lv_peer_id} '==' 0 ]; then
    Usage
    exit 1
fi

let lv_execute_delete=0
read -p 'Do you really want to continue? y/n : ' lv_key
if [ "$lv_key" == "y" ]; then
    lv_execute_delete=1
fi

if [ "$lv_execute_delete" == "0" ]; then
    echo "Not deleting the info about the peer: ${lv_peer_id}"
    exit 0
fi

echo "Deleting info about the peer: ${lv_peer_id}"

$JAVA_HOME/bin/java org.apache.hadoop.hbase.client.transactional.HBaseDCZK -delete -id ${lv_peer_id} 2>/dev/null
lv_exit=$?

exit ${lv_exit}
